### ISSUE TITLE
advice about the user agent database

### ISSUE THREAD

**Issue by zfb132** [fengzhizi715/user-agent-list#1]
This repo saved me much time, thanks a lot.  
I found a tiny question when reading content from the *.txt file.  Certain specific lines in `Mozilla.txt` and `Opera.txt`, such as [the 368th line in Mozilla.txt](https://github.com/fengzhizi715/user-agent-list/blob/be9c9eac08e41e9b5091e53668730d9666faba80/Mozilla.txt#L368), begin with space instead of non-whitespace characters.   
The versions of  user agents in these files maybe a little outdated, and it will be more perfect if you can change the url in [this file](https://github.com/fengzhizi715/user-agent-list/blob/master/src/main/java/cn/netdiscovery/ualist/Main.java#L14). There are some other websites, such as [whatismybrowser](https://developers.whatismybrowser.com/useragents/explore/), [fynas](http://www.fynas.com/ua), [udger](https://udger.com/resources/ua-list).

**Comment by fengzhizi715** [comment]
hi hi @zfb132 
这是一个不错的建议，我抽空加上
